2.10 让脚本报错后立即进入调试模式
=================================

|image0|

当你在使用 ``python xxx.py`` 这样的方法，执行 Python 脚本时，若因为代码
bug 导致异常未捕获，那整个程序便会终止退出。

这个时候，我们通常会去排查是什么原因导致的程序崩溃。

大家都知道，排查问题的思路，第一步肯定是去查看日志，若这个 bug
隐藏得比较深，只有在特定场景下才会现身，那么还需要开发者，复现这个
bug，方能优化代码。

复现有时候很难，有时候虽然简单，但是要伪造各种数据，相当麻烦。

**如果有一种方法能在程序崩溃后，立马进入调试模式该有多好啊？**

明哥都这么问了，那肯定是带着解决方案来的。

只要你在执行脚本行，加上 ``-i`` 参数，即可在脚本执行完毕后进入 Python
Shell 模式，方便你进行调试。

具体演示如下：

|image1|

需要注意的是：脚本执行完毕，有两种情况：

1. 正常退出
2. 异常退出

这两种都会进入 Python Shell，如果脚本并无异常，最终也会进入 Python Shell
模式，需要你手动退出

|image2|

如果希望脚本正确完成时自动退出，可以在脚本最后加上一行\ ``__import__("os")._exit(0)``

|image3|

.. |image0| image:: https://image.iswbm.com/20200804124133.png
.. |image1| image:: https://image.iswbm.com/20200801195950.png
.. |image2| image:: https://image.iswbm.com/20200801201110.png
.. |image3| image:: https://image.iswbm.com/20200607174235.png

